### ISSUE TITLE
uncaught exception: Callback specified for event modal:save is not a valid callback

### ISSUE THREAD

**Issue by hounded** [SolidInvoice/SolidInvoice#213]
Hi if I try to delete a invoice with the delete but I get this error, 

if you give me a bit of a pointer on where I would find this, I can try and fix it

**Comment by pierredup** [comment]
I think the issue here is due to the upgrade of the lodash version.
In previous versions of lodash, you could bind a callback function to a specific scope, but that was removed in later versions. Some of the code still relies on this functionality (Especially in [modal.js](https://github.com/SolidInvoice/SolidInvoice/blob/master/src/CoreBundle/Resources/public/js/modal.js#L52-L60) where `_.each` expects `this` to be the scope of the parent function due to the last argument.)
So the fix would be to update the usage of `_.each` to bind to the the correct scope
