### ISSUE TITLE
Installation fails: packages.json could not be downloaded

### ISSUE THREAD

**Issue by smilebasti** [SolidInvoice/SolidInvoice#374]
I tried installing SolidInvoice following the Docs for Distribution Package.
The Step Using Composer throws following Error:
[Composer\Downloader\TransportException]                                                                                
  The "https://repo.packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed o  
  ut.

I tried to get the package with wget. It timed out with the IPv4 Address but for the IPv6 it worked. (Retried it on multiple days) Now i am not sure how to fix it or integrate the file.

Thanks ahead

**Comment by pierredup** [comment]
@smilebasti This could be due to network issues on your side, where Composer can't connect to packagist.org.
The `packages.json` shouldn't be downloaded to the project, it is used to determine dependency versions which then gets downloaded to the `vendor` folder. So unfortunately, there is no manual way of installing the dependencies other than using `composer install`

**Comment by pierredup** [comment]
@smilebasti Closing for now, let me know if you still experience any issues.
