### ISSUE TITLE
process?action=createdb 404

### ISSUE THREAD

**Issue by ktwoncails** [SolidInvoice/SolidInvoice#379]
Issues installing SolidInvoice via the distribution package on Ubunutu 20 with PHP 7.4, MYSQL 8 and Apache.

Unable to get past the create database schema. There appears to be a 404 on process?action=createdb 
![SolidInvoice createdb](https://user-images.githubusercontent.com/83794059/117380499-a878a500-ae8e-11eb-86b5-891a678bf024.png)

Looking at the Apache logs, I receive this error
![apache-error-log](https://user-images.githubusercontent.com/83794059/117380542-c34b1980-ae8e-11eb-9839-97cd4ed06cd0.png)

Is there a way to manually install the database schema?

**Comment by ktwoncails** [comment]
It appears as it has something to do with the rewrite. 

install/process?action=createdb returns 404
app.php/install/process?action=createdb returns a result. 

Any thoughts?

**Comment by pierredup** [comment]
Hi, @ktwoncails. Thanks for the report.
This usually happens if you don't have the proper rewrites set up on your setup (as you rightfully noted as well). Which web server are you using (Nginx or apache), and what does your config look like?

This is already fixed in the master branch for the upcoming 2.1 release, so you can try using the master branch as well.

**Comment by ktwoncails** [comment]
Thanks @pierredup,
I'm running Apache/2.4.46. I just disabled rewrite and then re-enabled rewrite and it's now working as expected.
