### ISSUE TITLE
> Oops! An Error Occurred The server returned a "500 Internal Server Error". 

### ISSUE THREAD

**Issue by rongkn** [SolidInvoice/SolidInvoice#518]
@mariushosting  @pierredup still have a issue with 2.1.1.-dev get the following error when try and pay now , only credit works all the other fail with  Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

I have been pretty much unable to use the application to do anything have tried to redo with the latest docker image  

Log in screen is huge 
I will attach the screenshots 
![logon screen ](https://user-images.githubusercontent.com/32495778/198098518-357fe312-9b43-4de6-bbc3-05bd750750e3.JPG)
![Bank transfer for payment](https://user-images.githubusercontent.com/32495778/198098546-63d56e3a-2dad-4e50-bc0d-3160b61075a7.JPG)
![Bank transfer for payment error](https://user-images.githubusercontent.com/32495778/198098552-6437f7da-e017-41c0-84fb-ae866d2d3147.JPG)

_Originally posted by @rongkn in https://github.com/SolidInvoice/SolidInvoice/issues/459#issuecomment-1292392309_

**Comment by pierredup** [comment]
The `500 Internal Server Error` will be fixed with #535 and released as part of the 2.1.2 version.

> Log in screen is huge

That is due to the size of the image that has been uploaded for the logo. You can reduce the size of the image and upload a smaller image to fix the issue. We might add the option to resize the logo when uploading it in a future version.
