### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by manthanank** [SolidInvoice/SolidInvoice#618]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20230121_122331](https://user-images.githubusercontent.com/50883320/213784015-076b7410-dbeb-455e-91ec-2e442587e943.png)

**Desktop (please complete the following information):**
- OS: [e.g. iOS] - Windows
- Browser [e.g. chrome, safari] - Chrome
- Version [e.g. 22] - latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CherryDT** [comment]
The issue is that you are using Windows with Git Bash and didn't set npm's script shell to Git Bash though, so it uses CMD and many packages don't expect that.

The solution is `npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"` (or maybe `npm config set script-shell "C:\\Program Files (x86)\\Git\\bin\\bash.exe"` depending on your full path to the Git Bash executable).
